[build]
builder = "nixpacks"

[deploy]
startCommand = "node src/api/server-fullstack.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production.variables]
NODE_ENV = "production"
PORT = "3000"
LOG_LEVEL = "info"
DB_POOL_MIN = "2"
DB_POOL_MAX = "20"
API_RATE_LIMIT = "100"

[environments.production.volumes]
staticFiles = "/app/frontend/dist"