-- Ralph Storyteller SQLite Database Schema
-- Run with: sqlite3 ralph/stories.db < .claude/skills/ralph-storyteller/scripts/setup-db.sql

-- Input tables (populated by agents)
CREATE TABLE IF NOT EXISTS trends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic TEXT NOT NULL,
  relevance_score REAL DEFAULT 0.5,
  source TEXT, -- internal, news, policy, seasonal
  category_suggestion TEXT, -- seeds, growth, harvest, roots
  timeliness TEXT DEFAULT 'evergreen', -- evergreen, timely, urgent
  notes TEXT,
  related_programs TEXT, -- JSON array
  suggested_angle TEXT,
  captured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  processed BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS community_signals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  signal_type TEXT NOT NULL, -- story_gap, milestone, follow_up, community_request
  description TEXT,
  category TEXT, -- seeds, growth, harvest, roots
  priority INTEGER DEFAULT 3, -- 1-5, 1 is highest
  source TEXT,
  suggested_action TEXT,
  captured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  processed BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS research_findings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  topic TEXT NOT NULL,
  summary TEXT,
  sources TEXT, -- JSON array of URLs
  key_stats TEXT, -- JSON array
  relevance TEXT,
  suggested_use TEXT,
  captured_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Output tables (generated by Ralph)
CREATE TABLE IF NOT EXISTS story_briefs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  brief_id TEXT UNIQUE NOT NULL, -- matches PRD feature id
  title TEXT NOT NULL,
  category TEXT,
  angle TEXT,
  target_length TEXT,
  key_themes TEXT, -- JSON array
  suggested_sources TEXT, -- JSON array
  suggested_structure TEXT,
  brief_json TEXT, -- full brief as JSON
  status TEXT DEFAULT 'draft', -- draft, reviewed, approved, rejected
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME,
  reviewer_notes TEXT
);

CREATE TABLE IF NOT EXISTS article_drafts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  draft_id TEXT UNIQUE NOT NULL, -- matches PRD feature id
  brief_id TEXT,
  title TEXT NOT NULL,
  slug TEXT,
  excerpt TEXT,
  content TEXT, -- markdown content
  category TEXT,
  tags TEXT, -- JSON array
  reading_time_minutes INTEGER,
  featured_image_suggestion TEXT,
  status TEXT DEFAULT 'draft', -- draft, review, approved, rejected, published
  quality_score REAL,
  quality_notes TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME,
  reviewer_notes TEXT,
  published_at DATETIME,
  FOREIGN KEY (brief_id) REFERENCES story_briefs(brief_id)
);

CREATE TABLE IF NOT EXISTS social_content (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  campaign_id TEXT NOT NULL, -- matches PRD feature id
  article_id TEXT,
  platform TEXT NOT NULL, -- linkedin, twitter, facebook, instagram
  content TEXT NOT NULL,
  hashtags TEXT, -- JSON array
  image_suggestion TEXT,
  link_url TEXT,
  status TEXT DEFAULT 'draft', -- draft, approved, scheduled, published
  scheduled_for DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (article_id) REFERENCES article_drafts(draft_id)
);

-- Learning & iteration tracking
CREATE TABLE IF NOT EXISTS learnings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  iteration INTEGER,
  task_id TEXT,
  task_type TEXT, -- brief, article, social
  learning TEXT,
  category TEXT, -- content, process, quality, brand
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS iterations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  started_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  tasks_completed INTEGER DEFAULT 0,
  status TEXT DEFAULT 'running' -- running, completed, blocked
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_trends_processed ON trends(processed);
CREATE INDEX IF NOT EXISTS idx_signals_priority ON community_signals(priority, processed);
CREATE INDEX IF NOT EXISTS idx_drafts_status ON article_drafts(status);
CREATE INDEX IF NOT EXISTS idx_social_status ON social_content(status);

-- Views for easy querying
CREATE VIEW IF NOT EXISTS pending_trends AS
SELECT * FROM trends WHERE processed = 0 ORDER BY relevance_score DESC;

CREATE VIEW IF NOT EXISTS pending_signals AS
SELECT * FROM community_signals WHERE processed = 0 ORDER BY priority ASC;

CREATE VIEW IF NOT EXISTS content_stats AS
SELECT
  (SELECT COUNT(*) FROM story_briefs) as total_briefs,
  (SELECT COUNT(*) FROM story_briefs WHERE status = 'approved') as approved_briefs,
  (SELECT COUNT(*) FROM article_drafts) as total_drafts,
  (SELECT COUNT(*) FROM article_drafts WHERE status = 'approved') as approved_drafts,
  (SELECT COUNT(*) FROM social_content) as total_social,
  (SELECT COUNT(*) FROM social_content WHERE status = 'approved') as approved_social;
