// Re-export story.ts types, excluding names that conflict with stories.ts
export {
  type StoryMedia,
  type AIInsight,
  type MediaMetadata,
  type StoryCreate,
  type StoryUpdate,
  type StoryShare,
  type ShareTarget,
  type StoryExport,
  type StoryType,
  type VisibilityLevel,
  type StorySource,
  type InsightType,
  type SharePermission,
  type ReactionType,
  type StoryTemplate,
  type StoryPrompt,
  type CombinedStory,
  type StorySearchResult,
  type StoryRecommendation,
} from './story';

// Re-export user.ts types, excluding TimeSlot which conflicts with stories.ts
export {
  type User,
  type UserProfile,
  type YouthProfile,
  type Demographics,
  type JourneyEvent,
  type SkillsInterests,
  type Skill,
  type Achievement,
  type PrivacyControls,
  type ShareStorySettings,
  type PrivacySettings,
  type Address,
  type Location,
  type SocialLinks,
  type UserPreferences,
  type NotificationPreferences,
  type AccessibilitySettings,
  type UserActivity,
  type UserStats,
  type UserRole,
  type ProfileVisibility,
  type JourneyCategory,
  type ImpactLevel,
  type SkillLevel,
  type AchievementCategory,
  type MentorshipStatus,
  type UserCreate,
  type UserUpdate,
  type UserSearch,
  type UserSearchResult,
  type Availability,
  type DateRange,
  type Reference,
  type MentorPreferences,
  type AgeRange,
  type DayOfWeek,
  type CommunicationStyle,
  type MentorshipDuration,
} from './user';

export * from './airtable';
export * from './api';

// stories.ts wins for conflicting names: Story, StoryMetadata, StoryFilter,
// StoryCollection, StoryComment, StoryReaction, StoryAnalytics, TimeSlot
export * from './stories';

// Re-export gallery.ts types, excluding ContentType which conflicts with stories.ts
export {
  type GalleryItem,
  type RelatedItem,
  type ContentConnection,
  type GalleryEngagement,
  type DisplaySettings,
  type GalleryCollection,
  type CollectionCurator,
  type InclusionRule,
  type GalleryFeed,
  type GalleryFilter,
  type SearchResult,
  type SearchFacet,
  type FacetValue,
  type ContentGraph,
  type ContentNode,
  type ContentEdge,
  type ContentCluster,
  type RecommendationSet,
  type RecommendationItem,
  type GalleryAnalytics,
  type AnalyticsMetrics,
  type AnalyticsTrend,
  type CrossLinkAnalytics,
  type UserJourneyStep,
  SourceType,
  RelationshipType,
  ConnectionType,
  LayoutHint,
  AspectRatio,
  AnimationType,
  CollectionType,
  FilterType,
  SortOrder,
  AnalyticsPeriod,
  type GalleryViewProps,
  type GalleryLayout,
  LayoutType,
  type CrossLinkingConfig,
  type CrossLinkingAlgorithm,
  CrossLinkDisplayStyle,
  type GalleryContent,
  type ContentSource,
} from './gallery';