"use client";

import React from 'react';
import { SafetyDividendCalculator } from '@/components/intelligence/SafetyDividendCalculator';
import { Navigation } from '@/components/ui/navigation';
import { Calculator, ArrowRight, Info } from 'lucide-react';

export default function DividendToolPage() {
    return (
        <div className="min-h-screen bg-white text-black font-sans">
            <Navigation />

            <main className="page-content bg-gray-50 min-h-screen">
                <div className="container-justice py-12">
                    {/* Header - Industrial Tool Style */}
                    <div className="border-b-2 border-black pb-8 mb-12">
                        <div className="inline-flex items-center gap-2 bg-black text-white px-3 py-1 text-xs font-bold uppercase tracking-widest mb-4">
                            <Calculator className="w-3 h-3" /> Utility Tool
                        </div>
                        <h1 className="text-4xl md:text-5xl font-black uppercase tracking-tighter">
                            The Safety Dividend™<br />Calculator
                        </h1>
                        <p className="text-xl max-w-2xl mt-4 text-gray-700">
                            Quantify the "Net Present Safety" (NPS) generated by community interventions based on avoided fiscal liability.
                        </p>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-12">

                        {/* Left Column: Context */}
                        <div className="space-y-8">
                            <div className="border-2 border-black bg-white p-6">
                                <h3 className="font-bold uppercase tracking-widest text-sm mb-4 border-b border-gray-200 pb-2 flex items-center gap-2">
                                    <Info className="w-4 h-4" /> The Logic
                                </h3>
                                <div className="space-y-4 text-sm">
                                    <p>
                                        <strong>The Liability:</strong> We assume a <span className="bg-black text-white px-1 font-mono">$160,000/year</span> liability for every young person incarcerated (2024 Productivity Commission).
                                    </p>
                                    <p>
                                        <strong>The Pivot:</strong> By diverting just one young person, a program creates $160k in fiscal space.
                                    </p>
                                    <p>
                                        <strong>The Dividend:</strong> This tool calculates the 10-year NPS based on success rate and cohort size.
                                    </p>
                                </div>
                            </div>

                            <div className="bg-emerald-50 border-2 border-emerald-800 p-6 text-emerald-900">
                                <h3 className="font-bold uppercase tracking-widest text-sm mb-2">
                                    Why this matters
                                </h3>
                                <p className="text-sm leading-relaxed">
                                    "Cost" is a liability mindset. "Dividend" is an asset mindset. We shift the conversation from charity to investment.
                                </p>
                            </div>
                        </div>

                        {/* Right Column: The Calculator */}
                        <div className="lg:col-span-2">
                            <div className="border-2 border-black bg-white p-1">
                                <div className="border border-gray-100 p-6 md:p-8">
                                    <SafetyDividendCalculator />
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </main>
        </div>
    );
}
