-- Remote history placeholder
-- Version: 20260130033632
-- Purpose: records an existing remote migration history entry so local Supabase CLI state can be re-baselined.
-- This file is intentionally a no-op and must not be treated as a new schema change.
